import os

GITHUB_WEBHOOK_SECRET = os.getenv('GITHUB_WEBHOOK_SECRET').encode()
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
SERVER_URL_BASE = os.getenv('SERVER_URL_BASE').rstrip('/')
SERVER_PORT = int(os.getenv('SERVER_PORT', 80))
SERVER_HOSTNAME_PATTERN = os.getenv('SERVER_HOSTNAME_PATTERN')

HMAC_SECRET = TELEGRAM_BOT_TOKEN.encode('ascii')
GITHUB_APP_NAME = os.getenv('GITHUB_APP_NAME', 'telegram-githubbot-revised')
GITHUB_PRIVATE_KEY_PATH = os.getenv('GITHUB_PRIVATE_KEY_PATH')
GITHUB_APP_ID = os.getenv('GITHUB_APP_ID')
DATABASE_FILE = os.getenv('DATABASE_FILE', '/data/db.pickle')
GITHUB_OAUTH_CLIENT_ID = os.getenv('GITHUB_OAUTH_CLIENT_ID')
GITHUB_OAUTH_CLIENT_SECRET = os.getenv('GITHUB_OAUTH_CLIENT_SECRET')
DEBUG = bool(os.getenv('DEBUG', False))


DEFAULT_TRUNCATION_LIMIT = 4096

TELEGRAM_WEBHOOK_URL = SERVER_URL_BASE + '/' + TELEGRAM_BOT_TOKEN
GITHUB_OAUTH_REDIRECT_URI = SERVER_URL_BASE + '/github/auth'
